# Generated by Django 2.0.7 on 2018-11-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='body',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
